apps/relay/src/handlers.ts
apps/relay/src/server.ts
packages/connect/src/actions/authenticate.test.ts
packages/connect/src/actions/authenticate.ts
packages/connect/src/actions/connect.test.ts
packages/connect/src/actions/connect.ts
packages/connect/src/actions/status.test.ts
packages/connect/src/actions/status.ts
packages/connect/src/clients/createAppClient.test.ts
packages/connect/src/clients/createAppClient.ts
packages/connect/src/clients/createClient.test.ts
packages/connect/src/clients/createClient.ts
packages/connect/src/clients/createWalletClient.test.ts
packages/connect/src/clients/createWalletClient.ts
packages/connect/src/clients/index.ts
packages/connect/src/clients/transports/http.test.ts
packages/connect/src/clients/transports/http.ts
packages/connect/src/index.ts

Developers should be able to easily use connect without depending on a particular frontend UI like React.
Add client module to connect package. Use `AppClient` for frontend app actions (creating a connect channel and reading status), and `WalletClient` for wallet apps like Warpcast handling SIWE signing. 
We can continue building on this scaffolding as we build out the client library.
Although we'll only have a handful of actions, we're trying to create a Viem-like developer interface: 
```ts
import { createAppClient } from "@farcaster/connect";
const client = createAppClient({
relayURI: "https://connect.farcaster.xyz"
});
const { data: { channelToken } } = await client.connect({
siweUri: …
```

feat: app/wallet clients

---

apps/relay/package.json
package.json
packages/connect/package.json
packages/connect/src/actions/authenticate.test.ts
packages/connect/src/clients/createAuthClient.test.ts
packages/connect/src/clients/createAuthClient.ts
packages/connect/src/clients/index.ts
test/client/biome.json
test/client/jest.config.ts
test/client/package.json
test/client/src/e2e.test.ts
test/client/tsconfig.json

`WalletClient` is a confusing name, since it shadows the same name in Viem. Let's call this `AuthClient` instead.
- Rename `WalletClient` to `AuthClient`.
- Add e2e client test package

refactor: rename wallet client

---

packages/connect/package.json
packages/connect/src/actions/app/connect.test.ts
packages/connect/src/actions/app/status.test.ts
packages/connect/src/actions/app/verifySignInMessage.test.ts
packages/connect/src/actions/app/verifySignInMessage.ts
packages/connect/src/actions/auth/authenticate.test.ts
packages/connect/src/actions/auth/buildSignInMessage.test.ts
packages/connect/src/actions/auth/parseSignInURI.test.ts
packages/connect/src/actions/auth/parseSignInURI.ts
packages/connect/src/clients/createAppClient.test.ts
packages/connect/src/clients/createAppClient.ts
packages/connect/src/clients/createAuthClient.test.ts
packages/connect/src/clients/createAuthClient.ts
packages/connect/src/clients/createClient.ts
packages/connect/src/clients/ethereum/viem.ts
packages/connect/src/messages/build.ts
packages/connect/src/messages/parseSignInURI.test.ts
packages/connect/src/messages/parseSignInURI.ts
packages/connect/src/messages/verify.test.ts
packages/connect/src/messages/verify.ts
test/client/package.json
test/client/src/e2e.test.ts
yarn.lock

Add an auth actions to parse a sign in message from a protocol URI and an app action to verify sign in messages.

feat: parse sign in URI

---

packages/connect/src/actions/app/verifySignInMessage.ts
packages/connect/src/clients/ethereum/viem.ts
test/client/src/e2e.test.ts

SIWE uses Ethers to verify smart contract signatures. Add a `getProvider` function to `client.ethereum` that converts a Viem public client to an Ethers provider. Pass this to SIWE, so we use the configured RPC for contract signature verification.

feat: pass provider to SIWE

---

packages/connect/src/actions/app/verifySignInMessage.test.ts
packages/connect/src/clients/ethereum/viem.ts

`transport.url` is only set if the client is created with an explicit RPC URL. If it's not present, fall back to the network default.

fix: fall back to default RPC

---

packages/react/package.json

The React hooks/component package should be private for now.

fix: set react module private

---

.changeset/hungry-llamas-remember.md
packages/connect/README.md
packages/connect/src/actions/app/connect.test.ts
packages/connect/src/actions/app/connect.ts
packages/connect/src/actions/app/status.ts
packages/connect/src/actions/app/verifySignInMessage.test.ts
packages/connect/src/actions/app/verifySignInMessage.ts
packages/connect/src/actions/app/watchStatus.ts
packages/connect/src/actions/auth/authenticate.ts
packages/connect/src/actions/auth/buildSignInMessage.ts
packages/connect/src/actions/auth/parseSignInURI.ts
packages/connect/src/clients/transports/http.test.ts
packages/connect/src/clients/transports/http.ts
packages/connect/src/errors.ts
packages/connect/src/messages/build.test.ts
packages/connect/src/messages/build.ts
packages/connect/src/messages/verify.test.ts
packages/connect/src/messages/verify.ts

Use `neverthrow` for error handling internally. Catch and unwrap errors at the top level and return them as data.

feat: return error objects

---

packages/connect/README.md
packages/connect/src/actions/app/connect.test.ts
packages/connect/src/actions/app/status.test.ts
packages/connect/src/actions/app/verifySignInMessage.test.ts
packages/connect/src/actions/app/watchStatus.test.ts
packages/connect/src/actions/app/watchStatus.ts
packages/connect/src/clients/createAppClient.test.ts
packages/connect/src/clients/createAuthClient.test.ts
packages/connect/src/clients/createClient.test.ts
packages/connect/src/clients/createClient.ts
packages/react/src/hooks/useAppClient.ts
packages/react/src/hooks/useConnect.ts
packages/react/src/hooks/useSignIn.ts
packages/react/src/hooks/useVerifySignInMessage.ts
packages/react/src/hooks/useWatchStatus.ts

Extract `useAppClient`, `useConnect`,  `useWatchStatus` and `useVerifySignInMessage` from `useSignIn` hook.

refactor: split up hooks

---

apps/relay/.env.test
apps/relay/package.json
apps/relay/src/env.ts
apps/relay/src/handlers.ts
apps/relay/src/server.test.ts

In v1, only Warpcast is authorized to authenticate users.
Add a shared secret API key required to POST to `/authenticate` 

feat: add Warpcast auth key

---

apps/relay/src/schemas.ts
apps/relay/src/server.test.ts
packages/connect/.changeset/odd-laws-sneeze.md
packages/connect/src/actions/auth/authenticate.ts

We don't always have profile data for a user, so these parameters should be optional.

feat: optional userData parameters

---

packages/connect-kit/CHANGELOG.md
packages/connect-kit/package.json
packages/connect-kit/vite.config.ts

Roll up types into a single `connect-kit.d.ts` file.

fix: roll up types, publish v0.0.6

---

.changeset/spotty-chefs-tie.md
packages/connect/package.json
packages/connect/src/clients/ethereum/viem.ts
packages/connect/src/contracts/idRegistry.ts
yarn.lock

Remove `@farcaster/core` dependency from `@farcaster/connect`. We're only using this to read the ID Registry ABI and address, but it pulls in a 4MB library and requires browser polyfills. We should invest some attention in our build tooling for `@farcaster/core` and `@farcaster/hub-web` to make sure they're suitable for browsers.

fix: remove @farcaster/core dependency

---

.changeset/spotty-chefs-tie.md
packages/connect-kit/CHANGELOG.md
packages/connect-kit/package.json
packages/connect/CHANGELOG.md
packages/connect/package.json

Publish new packages, removing `@farcaster/core` dependency.

chore: publish connect@0.0.5, connect-kit@0.0.7

---

.changeset/great-jars-hammer.md
package.json
packages/connect-kit/vite.config.ts
packages/connect/package.json
yarn.lock

Two changes to reduce bundle size:
- Add ethers v6 at the same version required by `siwe`
- Remove unused node polyfills in `connect-kit`

chore: prune bundles

---

.changeset/great-jars-hammer.md
packages/connect-kit/CHANGELOG.md
packages/connect-kit/package.json
packages/connect/CHANGELOG.md
packages/connect/package.json

Release `connect@0.0.6` and `connect-kit@0.08`, with smaller bundle sizes.

chore: publish connect@0.0.6 and connect-kit@0.0.8

---

packages/connect-kit/CHANGELOG.md
packages/connect-kit/package.json
packages/connect/CHANGELOG.md
packages/connect/package.json
packages/connect/src/actions/auth/authenticate.test.ts
packages/connect/src/actions/auth/authenticate.ts
test/client/.env.test
test/client/CHANGELOG.md
test/client/package.json
test/client/src/e2e.test.ts

v1 requests to `/authenticate` are restricted to Warpcast using an auth key header. Add an `authKey` arg to the `authenticate` actoin.

fix: pass authKey in client

---

packages/connect-kit/src/hooks/useConnect.ts
packages/connect-kit/src/hooks/useSignIn.ts
packages/connect-kit/src/hooks/useVerifySignInMessage.ts
packages/connect/src/actions/app/connect.ts
packages/connect/src/actions/app/verifySignInMessage.test.ts
packages/connect/src/actions/app/verifySignInMessage.ts
packages/connect/src/messages/verify.test.ts
packages/connect/src/messages/verify.ts

Require an explicit `nonce` and `domain` in calls to `verifySignInMessage` and hooks.

feat: pass nonce and domain to verify

---

.changeset/fifty-brooms-double.md
packages/connect-kit/package.json
packages/connect-kit/vite.config.ts
yarn.lock

apg-js depends on the node Buffer implementation. Ship the polyfill to make life easier for devs.
Context: I spent ~1 hour trying to setup the Buffer polyfill in Nextjs with no success. The polyfill is relatively small.

feat: ship a polyfill for Buffer in connect-kit

---

.changeset/dull-rocks-clean.md
apps/relay/src/handlers.ts
apps/relay/src/server.test.ts

The relay server should return `nonce` from `/connect`.

fix: return nonce from connect

---

.github/workflows/ci.yml

We need to log in to Docker Hub in order to avoid being rate limited.
Use our standard read-only credentials.

fix: Log in to Docker Hub to avoid rate limit errors

---

packages/connect-kit/CHANGELOG.md
packages/connect-kit/package.json
packages/connect/CHANGELOG.md
packages/connect/package.json

Missed a changeset for the updated peer dependency in `connect`, use this one to force a version bump.

fix: add changeset for peer dependency change

---

.changeset/rotten-balloons-hang.md
packages/connect-kit/CHANGELOG.md
packages/connect-kit/package.json
packages/connect-kit/src/components/ConnectButton/ConnectButton.tsx

Remove the detached link mobile workaround from `ConnectButton`. (It doesn't work!)

fix: remove link workaround

---

packages/auth-client/CHANGELOG.md
packages/auth-client/package.json
packages/auth-client/src/clients/ethereum/connector.ts
packages/auth-client/src/clients/ethereum/ethers.ts
packages/auth-client/src/clients/ethereum/viemConnector.ts
packages/auth-client/src/messages/verify.ts
packages/auth-kit/CHANGELOG.md
packages/auth-kit/package.json

Add `ethers.ts` module to handle Ethers v5/v6 compatibility.

fix: ethers v5/v6 compatibility

---

packages/auth-client/CHANGELOG.md
packages/auth-client/package.json
packages/auth-client/src/clients/ethereum/ethers.ts
packages/auth-kit/CHANGELOG.md
packages/auth-kit/package.json

We also need to destructure `ethers` here to avoid an import error.

fix: ethers compatibility

---

.github/workflows/ci.yml
packages/auth-kit/CHANGELOG.md
packages/auth-kit/package.json
packages/auth-kit/src/hooks/useCreateChannel.ts

I accidentally undid this fix when working on renaming. The server returns the nonce in its create channel response, whether it was passed through from the frontend or generated server side, we can read it from there.

fix: read nonce value from relay response

---

.changeset/wise-horses-repeat.md
apps/relay/src/schemas.ts
apps/relay/src/server.test.ts

Allow optional port in domain.

fix: allow port in domain

---

.changeset/angry-hornets-divide.md
packages/auth-kit/src/components/AuthKitProvider/AuthKitProvider.tsx

`window.location` is not defined in a React Native environment.
Check for `window.location` in `AuthKitProvider`.

fix: check for window.location

---

.changeset/tiny-snails-burn.md
packages/auth-kit/src/components/AuthKitProvider/AuthKitProvider.tsx

All the configuration options on `AuthKitProvider` config are now optional.
Make the `config` prop optional on `AuthKitProvider`.

feat: make provider config optional

---

apps/relay/CHANGELOG.md
apps/relay/package.json
apps/relay/src/addresses.ts

Hubble 1.9.4 introduced a backwards incompatible rename of verifications from `VerificationAddEthAddress` to `VerificationAddAddress`. Add a check for both for now in the relay. (We should probably use GRPC here).

fix: verification fix

---

.changeset/sixty-meals-beg.md
packages/auth-kit/CHANGELOG.md
packages/auth-kit/package.json
packages/auth-kit/src/hooks/useSignIn.ts

Memoize `signIn` and `signOut` functions returned from `useSignIn` hook.

fix: memoize signIn and signOut

---

.changeset/four-months-decide.md
apps/relay/package.json
apps/relay/src/addresses.ts
apps/relay/src/env.ts
yarn.lock

Add fallback hub for loading connected addresses.

feat: add fallback hub

---

.changeset/green-hotels-explain.md
packages/auth-kit/src/components/FarcasterLogo.tsx
packages/auth-kit/src/components/QRCode.tsx
packages/auth-kit/src/components/QRCodeDialog/QRCodeDialog.tsx

The default AuthKit QR code can be difficult to scan.
Remove rounded dots, bump up default QR code size:

feat: improve QR code legibility

---

.changeset/violet-books-heal.md
packages/auth-kit/src/components/QRCodeDialog/QRCodeDialog.css.ts
packages/auth-kit/src/components/QRCodeDialog/QRCodeDialog.tsx

Add a clearer "Sign up" CTA to the sign in modal.

feat: add clearer sign up CTA to modal

---

packages/auth-kit/src/components/ActionButton/ActionButton.tsx
packages/auth-kit/src/components/SignInButton/SignInButton.tsx
packages/auth-kit/src/components/styles.css.ts

- Sign in fails frequently for me due to a race condition.
- When the Sign In button is clicked before the channel is established you cannot complete login.
- Open network inspector,  Slow network down to 3g, 
- Load the page and click the sign in button immediately (before the channel is fully created)
- Once the qr code modal pops up, scan the qr code
**Expected**: sign in to complete
**Actual**: it sits at the qr code modal – if you check the network inspector, the polling for /status never starts.
See video for root cause and explanation: https://share.cleanshot.com/y9FnghMw
Prevent the Sign In button from being clicked until a channel is established.
Alternate fixes considered:
- Don't reset state in useWatchStatus: can't reason about the scope of this change since consumed …

fix: login does not poll for status callback

---

.changeset/soft-rockets-doubt.md
packages/auth-client/src/clients/transports/http.ts

`onResponse` runs after the return statement hence doesn't run on the success condition.
call `onReponse` before returning from the function

fix: run onResponse on success

---

packages/auth-client/src/actions/app/watchStatus.test.ts
packages/auth-client/src/clients/transports/http.ts

#177 had the right idea, but we need to call `onResponse` on every response, not just success.
Move `onResponse` outside success code check.

fix: move call to onResponse

---

.changeset/late-dryers-appear.md
apps/relay/src/server.ts

The `/connect/*` routes on the relay are deprecated. According to our logs, nobody is calling them. Warpcast is still calling `/connect/authenticate`, which we should update in a separate change.
Remove `/connect/*` routes from relay server.

chore: remove deprecated routes

---

apps/relay/src/channels.test.ts
apps/relay/src/channels.ts
apps/relay/src/server.test.ts
apps/relay/src/tokens.ts

Reduce complexity of the SIWF QR code.
Use randomized 8-character codes instead of UUIDs for channel tokens.

feat: use shorter channel tokens

---

.changeset/long-islands-dream.md
apps/relay/src/handlers.ts
apps/relay/src/server.test.ts

Set generated nonce in `signatureParams`.

fix: set generated nonce in signature params

---

apps/relay/src/server.ts

Remove deprecated `/connect/authenticate` relay route.

chore: remove deprecated /connect/authenticate route

---

.changeset/loud-readers-watch.md
apps/relay/src/handlers.ts
apps/relay/src/server.test.ts
apps/relay/src/server.ts
packages/auth-client/src/actions/app/status.test.ts
packages/auth-client/src/actions/app/status.ts
packages/auth-client/src/actions/auth/authenticate.test.ts

To defend against “QR-jacking” attacks, pass the user agent and origin IP of the application opening the channel through the relay. Wallet clients can display this along with the sign in request, e.g. “requested from Chrome browser (Brooklyn, NY)” or similar.
Add `metadata.ip` and `metadata.userAgent` to relay session body.

feat: add request metadata to channel

---

.changeset/sixty-buttons-poke.md
packages/auth-client/src/messages/parseSignInURI.ts

Relax URL validation in `parseSignInURI` to allow URLs with channel token only.

chore: relax sign in URI validation

---

.changeset/lovely-mangos-itch.md
apps/relay/src/handlers.ts
apps/relay/src/server.test.ts
test/client/src/e2e.test.ts

Drop SIWE params from `constructUrl` in relay.

feat: drop SIWE params in constructUrl

---

.changeset/popular-flies-joke.md
apps/relay/src/addresses.ts

Bump up hub request timeouts to 5 seconds.

fix: bump relay timeouts

---

.changeset/brown-geese-pretend.md
apps/relay/src/logger.ts

We were hard coding this previously to `info`. Allow it to be customized.
Allow log level to be configured using LOG_LEVEL envar.

feat: Use LOG_LEVEL when setting log level

---

Dockerfile.relay

This allows you to define a health check for the container image in terms of a `curl` command.

feat: Add `curl` to Docker image for health checks

---

.github/workflows/ci.yml

Dependabot can't access our CI secrets. 
Skip Dockerhub login for Dependabot PRs.

chore: skip Docker login for Dependabot

---

.changeset/thirty-pumas-walk.md
apps/relay/src/server.ts

Use async/await style for plugin registration. (Fixes mixed style warning at startup)

fix: consistent plugin registration styles
