farcasterxyz/auth-monorepo

apps/relay/package.json
apps/relay/src/channels.ts
apps/relay/src/errors.ts
apps/relay/src/server.ts
docker-compose.yml

Add a `docker-compose.yml` that starts a local Redis and relay server.

chore: add docker-compose

---

apps/relay/src/handlers.ts
apps/relay/src/server.test.ts
packages/connect/src/actions/app/status.ts
packages/connect/src/actions/app/watchStatus.test.ts
packages/connect/src/actions/app/watchStatus.ts
packages/connect/src/clients/createAppClient.ts
packages/connect/src/clients/createClient.test.ts
packages/connect/src/clients/transports/http.test.ts
packages/connect/src/clients/transports/http.ts

- Add `watchStatus` action to app client.
- Add `poll` helper to `http`.

feat: watchStatus action

---

packages/README.md
packages/connect/src/actions/app/status.ts
packages/connect/src/actions/app/verifySignInMessage.test.ts
packages/connect/src/actions/auth/buildSignInMessage.test.ts
packages/connect/src/actions/auth/buildSignInMessage.ts
packages/connect/src/actions/auth/parseSignInURI.test.ts
packages/connect/src/messages/parseSignInURI.test.ts
packages/connect/src/messages/parseSignInURI.ts
test/client/src/e2e.test.ts

Add `README` to `@farcaster/connect` package.

feat: add basic docs

---

packages/connect/package.json
packages/connect/scripts/console.ts
packages/connect/src/actions/app/index.ts
packages/connect/src/actions/auth/index.ts
packages/connect/src/actions/index.ts
packages/connect/src/clients/ethereum/index.ts
packages/connect/src/clients/index.ts
packages/connect/src/clients/transports/index.ts
packages/connect/src/index.ts
packages/connect/src/messages/index.ts
packages/connect/tsconfig.json
packages/connect/tsup.config.ts

Clean up module exports.
Add Viem as peer dependency.
Add console script.

chore: module exports

---

.changeset/heavy-llamas-kiss.md

Add changeset for initial publication.

chore: add changeset

---

.changeset/heavy-llamas-kiss.md
packages/connect/CHANGELOG.md
packages/connect/package.json

Publish initial `@farcaster/connect` package.

chore: publish @farcaster/connect

---

apps/relay/src/handlers.ts
packages/react/package.json
packages/react/src/components/Demo/Demo.tsx
packages/react/src/components/Demo/index.ts
packages/react/src/components/SignInButton/SignInButton.tsx
packages/react/src/components/index.ts
packages/react/src/demo.tsx
packages/react/src/hooks/useSignIn.ts
packages/react/vite.config.ts
yarn.lock

- Add `useSignIn` demo hook. This is one huge hook right now, we should split it into multiple hooks + context.
- Pass through profile data from relay server.

feat: start useSignIn hook

---

packages/react/src/hooks/useAppClient.ts
packages/react/src/hooks/useSignIn.ts
packages/react/src/hooks/useWatchStatus.ts

Fix order of default arg overrides.

fix: override defaults with args

---

packages/react/src/components/ConnectButton/ConnectButton.tsx
packages/react/src/components/ConnectButton/index.ts
packages/react/src/components/Demo/Demo.tsx
packages/react/src/components/ErrorMessage/ErrorMessage.tsx
packages/react/src/components/ErrorMessage/index.ts
packages/react/src/components/ProfileButton/ProfileButton.tsx
packages/react/src/components/ProfileButton/index.ts
packages/react/src/components/QRCodeDialog/QRCodeDialog.tsx
packages/react/src/components/QRCodeDialog/index.tsx
packages/react/src/components/SignInButton/SignInButton.tsx
packages/react/src/hooks/useConnect.ts
packages/react/src/hooks/useSignIn.ts
packages/react/src/hooks/useVerifySignInMessage.ts
packages/react/src/hooks/useWatchStatus.ts

Split up the `Demo` component into reusable subcomponents.

refactor: split up connect components

---

packages/connect/package.json
packages/connect/src/clients/ethereum/viem.ts
yarn.lock

Fewer dependencies and allow pure ESM building (grpc packages used by hub-web are Common JS)

chore: user @farcaster/core instead of @farcaster/hub-web

---

packages/react/src/components/ConnectButton/ConnectButton.tsx
packages/react/src/components/ConnectKitProvider/ConnectKitProvider.tsx
packages/react/src/components/ConnectKitProvider/index.ts
packages/react/src/components/Demo/Demo.tsx
packages/react/src/hooks/useAppClient.ts
packages/react/src/hooks/useConnect.ts
packages/react/src/hooks/useConnectKitContext.ts
packages/react/src/hooks/useSignIn.ts
packages/react/src/hooks/useUserData.ts
packages/react/src/hooks/useVerifySignInMessage.ts
packages/react/src/hooks/useWatchStatus.ts

Extract `ConnectKitProvider` and context.

feat: extract provider and context

---

.changeset/slimy-beans-applaud.md
packages/connect-kit/CHANGELOG.md
packages/connect-kit/package.json
packages/connect-kit/src/components/ConnectKitProvider/index.ts
packages/connect-kit/src/components/index.ts
packages/connect-kit/src/hooks/index.ts
packages/connect-kit/src/hooks/useConnect.ts
packages/connect-kit/src/hooks/useSignIn.ts
packages/connect-kit/src/hooks/useVerifySignInMessage.ts
packages/connect-kit/src/hooks/useWatchStatus.ts
packages/connect-kit/tsconfig.node.json
packages/connect-kit/vite.config.ts
packages/connect/CHANGELOG.md
packages/connect/package.json

Publish `@farcaster/connect-kit@0.02`

chore: publish connect-kit@0.0.2

---

.changeset/fifty-tools-cover.md
packages/connect-kit/CHANGELOG.md
packages/connect-kit/package.json

Our `package.json` excluded `dist` from the published package.

fix: fix package dist

---

packages/connect-kit/CHANGELOG.md
packages/connect-kit/package.json

Include `style.css` in the published package.

chore: add css to package, release 0.0.4

---

packages/connect-kit/CHANGELOG.md
packages/connect-kit/package.json
packages/connect-kit/src/components/ConnectKitProvider/ConnectKitProvider.tsx
packages/connect-kit/vite.config.ts
yarn.lock

Include type definitions in Vite build output.

fix: bundle types, publish v0.0.5

---

.changeset/stale-carrots-wave.md
packages/connect-kit/src/components/ConnectButton/ConnectButton.tsx
packages/connect-kit/src/components/ConnectKitProvider/ConnectKitProvider.tsx
packages/connect-kit/src/components/Demo/Demo.tsx
packages/connect-kit/src/components/QRCodeDialog/QRCodeDialog.tsx
packages/connect-kit/src/hooks/useConnect.ts
packages/connect-kit/src/hooks/useSignIn.ts
packages/connect-kit/src/hooks/useWatchStatus.ts
packages/connect/scripts/console.ts
packages/connect/src/actions/app/connect.ts
packages/connect/src/actions/app/status.test.ts
packages/connect/src/actions/app/watchStatus.ts
packages/connect/src/actions/auth/authenticate.test.ts
packages/connect/src/actions/auth/buildSignInMessage.test.ts
packages/connect/src/actions/auth/parseSignInURI.test.ts
packages/connect/src/clients/createAppClient.test.ts
packages/connect/src/clients/createAuthClient.test.ts
packages/connect/src/clients/createClient.test.ts
packages/connect/src/clients/createClient.ts
packages/connect/src/clients/transports/http.test.ts
packages/connect/src/clients/transports/http.ts

Lowercase `URL` and `URI` (more consistent with our other packages). 
Rename `relayURI` `relay`.
Add additional connect params as `ConnectButton` props.

chore: lowercase URI/URL

---

.changeset/six-eyes-grab.md
apps/relay/package.json
apps/relay/src/env.ts
apps/relay/src/handlers.ts
apps/relay/src/server.test.ts
packages/connect/src/actions/app/status.test.ts
packages/connect/src/actions/auth/authenticate.test.ts
packages/connect/src/actions/auth/parseSignInURI.test.ts
packages/connect/src/messages/parseSignInURI.test.ts
test/client/src/e2e.test.ts
yarn.lock

Use Warpcast URLs instead of protocol handlers.
Rename `connectURI` `connectUri` in relay server response.

chore: use Warpcast URLs

---

.changeset/friendly-jeans-pay.md
packages/connect-kit/src/components/ConnectKitProvider/ConnectKitProvider.tsx
packages/connect-kit/src/components/Demo/Demo.tsx
packages/connect-kit/src/hooks/useSignInMessage.ts

Add `useSignInMessage` hook to read SIWF message and signature from context.

feat: useSignInMessage hook

---

packages/connect-kit/src/hooks/index.ts

Export `useSignInMessage` hook.

fix: export useSignInMessage

---

.changeset/friendly-jeans-pay.md
.changeset/six-eyes-grab.md
.changeset/stale-carrots-wave.md
apps/relay/CHANGELOG.md
apps/relay/package.json
packages/connect-kit/CHANGELOG.md
packages/connect-kit/package.json
packages/connect/CHANGELOG.md
packages/connect/package.json
test/client/CHANGELOG.md
test/client/package.json

Use Warpcast URLs instead of `farcaster://` protocol URLs.
Add `useSignInMessage` hook.

chore: release packages

---

packages/connect/src/messages/verify.ts

dont import ethers code

---

.changeset/tidy-clouds-taste.md
packages/connect-kit/src/components/ConnectKitProvider/ConnectKitProvider.tsx
packages/connect-kit/src/components/Demo/Demo.tsx
packages/connect-kit/src/hooks/useConnect.ts
packages/connect-kit/src/hooks/useSignIn.ts
packages/connect-kit/src/hooks/useVerifySignInMessage.ts
packages/connect-kit/src/hooks/useWatchStatus.ts

Add `onSuccess`/`onError` callbacks to hooks and components

feat: hook/component callbacks

---

.changeset/blue-trainers-pump.md
packages/connect-kit/package.json
packages/connect/package.json

Change `viem` to a peer dependency.

chore: viem peer dependency

---

.changeset/weak-keys-admire.md
packages/connect-kit/src/components/ConnectKitProvider/ConnectKitProvider.tsx
packages/connect-kit/src/components/Demo/Demo.tsx
packages/connect-kit/src/hooks/useConnect.ts

Set `siweUri` and `domain` on config, rather than as props on `ConnectButton`

feat: hoist siweUri and domain to config

---

.changeset/blue-trainers-pump.md
.changeset/dry-cats-hug.md
.changeset/tidy-clouds-taste.md
.changeset/weak-keys-admire.md
packages/connect-kit/CHANGELOG.md
packages/connect-kit/package.json
packages/connect/CHANGELOG.md
packages/connect/package.json

chore: publish packages

---

.changeset/green-grapes-add.md
examples/with-next-auth/pages/index.tsx
packages/connect-kit/CHANGELOG.md
packages/connect-kit/package.json
packages/connect-kit/src/components/ConnectKitProvider/ConnectKitProvider.tsx
packages/connect/CHANGELOG.md
packages/connect/README.md
packages/connect/package.json
packages/connect/src/actions/app/connect.test.ts
packages/connect/src/actions/app/status.test.ts
packages/connect/src/actions/auth/authenticate.test.ts
packages/connect/src/actions/auth/buildSignInMessage.test.ts
packages/connect/src/actions/auth/parseSignInURI.test.ts
packages/connect/src/clients/createAppClient.test.ts
packages/connect/src/clients/createAuthClient.test.ts
packages/connect/src/clients/createClient.test.ts
packages/connect/src/clients/createClient.ts
packages/connect/src/clients/transports/http.test.ts

We're using `relay.farcaster.xyz` as the relay URL.

chore: update relay URL

---

.changeset/tough-dolphins-stare.md
packages/connect-kit/CHANGELOG.md
packages/connect-kit/package.json
packages/connect-kit/src/hooks/useConnect.ts

The connect response isn't returning a nonce. Use the local value since we have it.

fix: use local nonce value

---

.changeset/violet-poets-smell.md
packages/connect-kit/src/components/ConnectKitProvider/ConnectKitProvider.tsx

Convert `relay` to an optional parameter in `config`.

feat: optional relay

---

packages/connect/src/messages/verify.ts

fix: remove console.log

---

examples/frontend-only/package.json
examples/frontend-only/src/App.tsx
examples/frontend-only/yarn.lock
examples/with-next-auth/package.json
examples/with-next-auth/pages/api/auth/[...nextauth].ts
examples/with-next-auth/pages/index.tsx
examples/with-next-auth/yarn.lock
packages/auth-client/CHANGELOG.md
packages/auth-client/package.json
packages/auth-client/src/messages/validate.test.ts
packages/auth-client/src/messages/validate.ts
packages/auth-kit/CHANGELOG.md
packages/auth-kit/package.json

Update example apps. Accept `"Farcaster Connect"` as SIWE statement for backwards compatibility.

chore: update examples

---

examples/frontend-only/package.json
examples/frontend-only/yarn.lock
examples/with-next-auth/package.json
examples/with-next-auth/pages/api/auth/[...nextauth].ts
examples/with-next-auth/yarn.lock

Update dependencies in example apps.

chore: update example app dependencies

---

examples/frontend-only/README.md
examples/frontend-only/package.json
examples/frontend-only/yarn.lock
examples/with-next-auth/README.md
examples/with-next-auth/package.json
examples/with-next-auth/yarn.lock

Update example app dependencies and READMEs.

chore: update demo apps

---

README.md
package.json
packages/auth-client/README.md
test/client/src/e2e.test.ts

Update top level README, fix a few stray references to "connect".

chore: clean up stray renames

---

packages/auth-kit/README.md

Add troubleshooting section from #75. (Thank you @androidsixteen!)
Close #75

chore: add troubleshooting section to README

---

examples/frontend-only/README.md
examples/frontend-only/index.html
examples/frontend-only/package.json
examples/frontend-only/src/App.tsx
examples/frontend-only/yarn.lock
examples/with-next-auth/README.md
examples/with-next-auth/package.json
examples/with-next-auth/pages/index.tsx
examples/with-next-auth/yarn.lock

Update example apps: slightly nicer styling, better READMEs.

feat: update example apps

---

examples/frontend-only/package.json
examples/frontend-only/src/App.tsx
examples/frontend-only/yarn.lock
examples/with-next-auth/package.json
examples/with-next-auth/pages/index.tsx
examples/with-next-auth/yarn.lock

Add "clone repo and run" oneliners to example apps.

feat: add checkout oneliners

---

.changeset/smart-kangaroos-cough.md
packages/auth-kit/src/components/AuthKitProvider/AuthKitProvider.tsx
packages/auth-kit/src/components/Button.tsx
packages/auth-kit/src/components/Demo/Demo.tsx
packages/auth-kit/src/components/FarcasterLogo.tsx
packages/auth-kit/src/components/ProfileButton/ProfileButton.tsx
packages/auth-kit/src/components/SignInButton/SignInButton.tsx
packages/auth-kit/src/components/styles.css.ts
packages/auth-kit/src/hooks/useCreateChannel.ts
packages/auth-kit/src/hooks/useDetectClickOutside.ts
packages/auth-kit/src/hooks/useSignIn.ts
packages/auth-kit/src/hooks/useVerifySignInMessage.ts
packages/auth-kit/src/hooks/useWatchStatus.ts

There should be a simple way to sign out and clear the SIWF state.
Add a "Sign out" button to the logged in state.

feat: add sign out button

---

.changeset/friendly-impalas-speak.md
packages/auth-kit/src/components/Demo/Demo.tsx
packages/auth-kit/src/components/SignInButton/SignInButton.tsx

Memoize callbacks in `SignInButton` component.

fix: memoize signin callbacks

---

.changeset/big-suns-confess.md
packages/auth-kit/src/components/Dialog/Dialog.tsx
packages/auth-kit/src/components/ProfileButton/ProfileButton.css.ts
packages/auth-kit/src/components/ProfileButton/ProfileButton.tsx
packages/auth-kit/src/components/QRCode.tsx
packages/auth-kit/src/components/QRCodeDialog/QRCodeDialog.tsx
packages/auth-kit/src/components/SignInButton/SignInButton.css.ts
packages/auth-kit/src/components/SignInButton/SignInButton.tsx
packages/auth-kit/src/components/SignOutButton/SignOutButton.css.ts
packages/auth-kit/src/components/SignOutButton/SignOutButton.tsx
packages/auth-kit/src/components/SignOutButton/index.ts
packages/auth-kit/src/components/styles.css.ts

Refactor CSS from inline styles to classes. Add empty top-level classes to sign in button, QR code dialog, and profile button.

feat: add CSS classes to components

---

.changeset/famous-glasses-exercise.md
packages/auth-kit/src/components/Button.tsx
packages/auth-kit/src/components/SignInButton/SignInButton.tsx
packages/auth-kit/src/hooks/useSignIn.ts
packages/auth-kit/src/hooks/useWatchStatus.ts

Fix #108 
Create a new channel on first render. Return `watch` from `useWatchStatus`. Move redirect into `onClick` handler.

fix: iOS redirect delay

---

.changeset/spicy-yaks-film.md
packages/auth-kit/src/components/AuthKitProvider/AuthKitProvider.tsx
packages/auth-kit/src/components/Demo/Demo.tsx

Use window host and URL as defaults for host/siweUri.

feat: add siweUri and host defaults

---

.changeset/itchy-stingrays-grab.md
apps/relay/fastify.d.ts
apps/relay/package.json
apps/relay/src/addresses.ts
apps/relay/src/env.ts
apps/relay/src/handlers.ts
apps/relay/src/server.test.ts
apps/relay/src/server.ts
packages/auth-client/src/actions/app/status.ts
packages/auth-client/src/actions/app/watchStatus.ts
test/client/src/e2e.test.ts
yarn.lock

Return verified addresses and custody address from the auth server.

feat: return custody and verified addresses

---

.changeset/plenty-steaks-lay.md
packages/auth-kit/src/components/ProfileButton/ProfileButton.tsx
packages/auth-kit/src/components/SignInButton/SignInButton.tsx

Not everyone will want to show the Sign Out button.
Add an optional `disableSignOut` prop to `SignInButton`

feat: optional disableSignOut prop

---

packages/auth-client/README.md
packages/auth-kit/README.md
packages/auth-kit/src/components/AuthKitProvider/AuthKitProvider.tsx
packages/auth-kit/src/components/Demo/Demo.tsx
packages/auth-kit/src/components/SignOutButton/SignOutButton.css.ts
packages/auth-kit/src/components/SignOutButton/SignOutButton.tsx

It's useful to know the user's custody address and verified addresses.
Expose custody address/verifications in user profile.

feat: add verifications to profile

---

.changeset/angry-hornets-divide.md
.changeset/fuzzy-weeks-poke.md
.changeset/plenty-steaks-lay.md
.changeset/tiny-snails-burn.md
packages/auth-kit/CHANGELOG.md
packages/auth-kit/package.json

chore: version auth-kit

---

.changeset/poor-bottles-notice.md
packages/auth-kit/CHANGELOG.md
packages/auth-kit/package.json
packages/auth-kit/src/components/Demo/Demo.tsx
packages/auth-kit/src/components/ProfileButton/ProfileButton.tsx
packages/auth-kit/src/components/SignInButton/SignInButton.tsx
packages/auth-kit/src/hooks/useWatchStatus.ts

Add `onSignOut` callback to `SignInButton`.

feat: sign out callback

---

.changeset/great-papayas-complain.md
packages/auth-kit/CHANGELOG.md
packages/auth-kit/package.json
packages/auth-kit/src/components/AuthKitProvider/AuthKitProvider.tsx

Check for both `window` and `window.location`.

fix: window conditional bug

---

packages/auth-kit/CHANGELOG.md
packages/auth-kit/package.json
packages/auth-kit/src/components/AuthKitProvider/AuthKitProvider.tsx

fix: check with typeof

---

examples/frontend-only/package.json
examples/frontend-only/src/App.tsx
examples/frontend-only/yarn.lock
examples/with-next-auth/package.json
examples/with-next-auth/pages/api/auth/[...nextauth].ts
examples/with-next-auth/pages/index.tsx
examples/with-next-auth/yarn.lock

Update example apps to `auth-kit@0.1.x`

feat: update example apps with auth-kit@0.1.x

---

examples/frontend-only/package.json
examples/frontend-only/vite.config.ts
examples/frontend-only/yarn.lock

Changes from #136 (need to update build settings and secrets to support external PRs).
Close #136

fix: vite buffer polyfill

---

examples/frontend-only/yarn.lock

Update Vite in frontend example app.

chore: update vite

---

.changeset/slow-laws-tap.md
apps/relay/src/handlers.ts
apps/relay/src/server.test.ts
apps/relay/src/server.ts

chore: return response in async handlers

---

apps/relay/src/env.ts

Info messages aren't terribly useful.
Log only warnings or higher levels.

chore: Change default log level to `warn`

---

.changeset/green-hotels-explain.md
packages/auth-kit/CHANGELOG.md
packages/auth-kit/package.json

chore: version packages

---

packages/auth-kit/src/components/FarcasterLogo.tsx

Describe why this issue should be fixed and link to any relevant design docs, issues or other relevant items.
Describe the changes being made in 1-2 concise sentences.

fix: remove duplicate viewBox prop

---

examples/frontend-only/src/App.tsx

Describe why this issue should be fixed and link to any relevant design docs, issues or other relevant items.
Describe the changes being made in 1-2 concise sentences.

fix: nested `pre` warn

---

.changeset/quick-laws-smoke.md
apps/relay/package.json
apps/relay/src/app.ts
apps/relay/src/env.ts
apps/relay/src/tracing.ts
test/client/src/e2e.test.ts
yarn.lock

We're collecting logs, but we'd like better observability for the relay using dd-trace.
Configure and enable Datadog tracing for the auth relay.

chore: add dd-trace

---

apps/relay/src/app.ts

fix: tracing import

---

.changeset/thirty-geckos-study.md
apps/relay/src/env.ts

Add `OP_MAINNET_RPC_URL` env var.

chore: add RPC URL env var

---

yarn.lock

Upgrade relay core dependencies.

chore: upgrade relay dependencies

---

.changeset/early-llamas-occur.md
apps/relay/package.json
apps/relay/src/addresses.ts
apps/relay/src/env.ts
apps/relay/src/handlers.ts
apps/relay/src/hubs.ts
yarn.lock

The GRPC client is more reliable than Hub HTTP APIs.
Retrieve verifications using Hub GRPC client.

chore: use GRPC hub client

---

apps/relay/package.json
yarn.lock

Remove unused Ethers.js dependency.

chore: remove unused dependency

---

apps/relay/package.json
yarn.lock

Reverts farcasterxyz/auth-monorepo#196

Revert "chore: remove unused dependency"

---

apps/relay/src/handlers.ts

Fix fallthrough in relay error handler.

fix: error handler

---

.changeset/fifty-experts-love.md
apps/relay/src/handlers.ts
apps/relay/src/server.test.ts
packages/auth-client/src/actions/app/status.test.ts
packages/auth-client/src/actions/app/status.ts
packages/auth-kit/src/components/AuthKitProvider/AuthKitProvider.tsx

Simplify SIWF QR codes by passing SIWE parameters in the channel body.
Add `signatureParams` to channel body and `/status` response.

feat: pass siwe params in channel body

---

.changeset/eight-seahorses-laugh.md
packages/auth-kit/src/components/QRCode.tsx
packages/auth-kit/src/components/QRCodeDialog/QRCodeDialog.css.ts
packages/auth-kit/src/components/QRCodeDialog/QRCodeDialog.tsx
packages/auth-kit/src/components/styles.css.ts

Simplify QR codes and restyle dialog.

feat: restyle QR code dialog

---

.changeset/lovely-mangos-itch.md
apps/relay/CHANGELOG.md
apps/relay/package.json

chore: version auth-relay

---

.changeset/mean-baboons-collect.md
packages/auth-kit/src/components/SignInButton/SignInButton.tsx

Follow up to #200. Add changeset, use `window.open` in `SignInButton`.

fix: use window.open for mobile links

---

Dockerfile.relay

This didn't work because we weren't running as the right user.

Fix order of curl installation

---

.github/workflows/ci.yml

fix: ci workflow syntax

---

apps/relay/package.json
apps/relay/src/server.test.ts
examples/authkit-expo-demo/package.json
examples/frontend-only/package.json
examples/frontend-only/src/App.tsx
examples/with-next-auth/package.json
examples/with-next-auth/pages/api/auth/[...nextauth].ts
packages/auth-client/package.json
packages/auth-kit/package.json
test/client/package.json
yarn.lock

chore: dependency upgrades

---

yarn.lock

Update auth relay dependencies.

chore: relay dependencies

---

.changeset/real-mangos-give.md
apps/relay/package.json
apps/relay/src/handlers.ts
examples/frontend-only/package.json
examples/frontend-only/src/App.tsx
examples/with-next-auth/package.json
yarn.lock

Remove ethers.js from dependent apps.

chore: remove Ethers dependencies

---

.changeset/quick-books-search.md
apps/relay/src/env.ts
apps/relay/src/server.test.ts
packages/auth-client/src/actions/app/status.test.ts
packages/auth-client/src/actions/auth/authenticate.test.ts
packages/auth-client/src/actions/auth/parseSignInURI.test.ts
packages/auth-client/src/messages/parseSignInURI.test.ts
packages/auth-kit/src/components/ProfileButton/ProfileButton.tsx

Describe why this issue should be fixed and link to any relevant design docs, issues or other relevant items.
Describe the changes being made in 1-2 concise sentences.

chore: replace Warpcast URLs with Farcaster
